In [1]:
import numpy as np 
import pandas as pd
from scipy.stats import poisson, chi2

import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

n = 600
index = ["Поток 1", "Поток 2"]
columns = [2, 3, 4, 5]
data_df = pd.DataFrame(columns=columns, index = pd.Index(index))
data_df.loc["Поток 1", :] = np.array([33, 43, 80, 144])
data_df.loc["Поток 2", :] = np.array([39, 35, 72, 154])
data_df

          2   3   4    5
Поток 1  33  43  80  144
Поток 2  39  35  72  154

In [2]:
# Найдем ню, чтобы потом использовать ее для нахождения дельты
nu_df = pd.DataFrame(columns=[1, 2, 3, 4], index=pd.Index(["nu_i"]))
nu_df.loc["nu_i", :] = np.array([np.sum(data_df.loc[pd.Index(index), columns[i]])/n for i in range(0, 4)])
nu_df

         1     2         3         4
nu_i  0.12  0.13  0.253333  0.496667

In [3]:
# Находим дельту по формуле
def delta_s(s: int, nu: pd.DataFrame, df: pd.DataFrame):
    n_s = np.sum(df.loc[index[s-1], :])
    _delta_s = 0
    for j in (1, 2, 3, 4):
        m_ij = df.loc[index[s-1], columns[j-1]]
        nu_j = nu.loc["nu_i", j]
        _delta_s += (m_ij - n_s*nu_j)**2/(n_s*nu_j)
    return _delta_s

delta_df = pd.DataFrame(columns=[1, 2], index=pd.Index(["delta_s"]))
delta_df.loc["delta_s", :] = np.array([delta_s(s, nu_df, data_df) for s in (1, 2)])
delta_df

                1         2
delta_s  1.038568  1.038568

In [4]:
delta = np.sum(delta_df.loc["delta_s", :])
delta

2.0771359218904255

In [5]:
k = 4
l = 2
sf = chi2.sf(delta, (k-1)*(l-1))
print(sf)

0.5565521530460769

## p-value > 0.05, следовательно результат не стат. значимый, не можем отвергнуть H0.